# Generated by Django 5.2.1 on 2025-05-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('power', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=255)),
                ('side_effect', models.JSONField()),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('defense', models.IntegerField(default=1)),
                ('spattack', models.IntegerField(default=1)),
                ('spdefense', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('precision', models.IntegerField(default=100)),
                ('evasion', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movepool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.ManyToManyField(related_name='movepool', to='api.move')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sprite_path', models.CharField(max_length=100)),
                ('Ivs', models.JSONField()),
                ('Evs', models.JSONField()),
                ('Movepool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monsterMvP', to='api.movepool')),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monsterStats', to='api.stats')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mon1', to='api.monster')),
                ('mon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mon2', to='api.monster')),
                ('mon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mon3', to='api.monster')),
                ('mon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mon4', to='api.monster')),
                ('mon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mon5', to='api.monster')),
                ('mon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mon6', to='api.monster')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
